[package]
name = "xsynth"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1.7.2"
cpal = "0.13.3"
crossbeam-channel = "0.5.1"
midi-tools-rs = { git = "https://github.com/arduano/midi-tools-rs" }
rodio = "0.14.0"
soundfont = "0.0.0"
spin_sleep = "1.0.0"

[build-dependencies]
cbindgen = "0.20.0"