[workspace]

members = ["core", "realtime", "kdmapi", "soundfonts", "render", "soundfonts/soundfonts_macro"]

[profile.release]
codegen-units = 1
lto = true

[profile.release-with-debug]
inherits = "release"
debug = true
