[package]
name = "xsynth"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atomic_refcell = "0.1.7"
bytemuck = "1.7.2"
cpal = "0.13.3"
crossbeam-channel = "0.5.1"
lazy_static = "1.4.0"
midi-tools-rs = { git = "https://github.com/arduano/midi-tools-rs" }
rayon = "1.5.1"
simdeez = "1.0.7"
soundfont = "0.0.0"
spin_sleep = "1.0.0"
to_vec = "0.1.0"

[build-dependencies]
cbindgen = "0.20.0"
