[workspace]

members = [
    "core",
    "realtime",
    "kdmapi",
    "soundfonts",
    "render",

    "daw-plugin",
    "daw-plugin/xtask",
]

[profile.release]
codegen-units = 1
lto = true

[profile.release-with-debug]
inherits = "release"
debug = true
