[package]
name = "xsynth"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atomic_refcell = "0.1.7"
bytemuck = "1.7.2"
cpal = "0.13.3"
crossbeam-channel = "0.5.1"
lazy_static = "1.4.0"
midi-tools-rs = { git = "https://github.com/arduano/midi-tools-rs", rev = "526df6c" }
rayon = "1.5.1"
simdeez = { git = "https://github.com/arduano/simdeez", rev = "d72e9a1" }
sofiza = { git = "https://github.com/arduano/sofiza", rev = "4a013a6" }
soundfont = "0.0.0"
spin_sleep = "1.0.0"
to_vec = "0.1.0"
wav = "1.0.0"

[build-dependencies]
cbindgen = "0.20.0"

[profile.release]
codegen-units = 1
lto = true
