[workspace]
resolver = "2"
members = ["core", "realtime", "kdmapi", "soundfonts", "render"]

[workspace.package]
authors = ["Arduano", "MBMS"]
version = "0.1.0"
license = "MIT"
edition = "2021"
homepage = "https://github.com/arduano/xsynth"
repository = "https://github.com/arduano/xsynth"
readme = "README.md"
keywords = ["midi", "synthesizer", "soundfont"]
categories = ["multimedia::audio"]

[profile.release]
codegen-units = 1
lto = true

[profile.release-with-debug]
inherits = "release"
debug = true
