[package]
name = "kdmapi"
version = "0.1.0"
edition = "2021"

[lib]
name = "OmniMIDI"
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.13.3"
core = { path = "../core", package = "xsynth-core" }
realtime = { path = "../realtime", package = "xsynth-realtime" }
winapi = "0.3.9"
cfg-if = "1.0.0"
