[package]
name = "xsynth-render"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
core = { path = "../core", package = "xsynth-core" }
crossbeam-channel = "0.5.1"
hound = "3.5.0"
rayon = "1.5.3"
midi-toolkit-rs = { git = "https://github.com/arduano/midi-toolkit-rs", rev = "26747a3" }
spin_sleep = "1.0.0"
atomic_float = "0.1.0"
thiserror = "1.0.31"
