pub const XSYNTH_AUDIO_EVENT_NOTEON: u16 = 0;
pub const XSYNTH_AUDIO_EVENT_NOTEOFF: u16 = 1;
pub const XSYNTH_AUDIO_EVENT_ALLNOTESOFF: u16 = 2;
pub const XSYNTH_AUDIO_EVENT_ALLNOTESKILLED: u16 = 3;
pub const XSYNTH_AUDIO_EVENT_RESETCONTROL: u16 = 4;
pub const XSYNTH_AUDIO_EVENT_CONTROL: u16 = 5;
pub const XSYNTH_AUDIO_EVENT_PROGRAMCHANGE: u16 = 6;
pub const XSYNTH_AUDIO_EVENT_PITCH: u16 = 7;
pub const XSYNTH_AUDIO_EVENT_FINETUNE: u16 = 8;
pub const XSYNTH_AUDIO_EVENT_COARSETUNE: u16 = 9;

pub const XSYNTH_CONFIG_SETLAYERS: u16 = 0;
pub const XSYNTH_CONFIG_SETSOUNDFONT: u16 = 1;
pub const XSYNTH_CONFIG_SETPERCUSSIONMODE: u16 = 2;

pub const XSYNTH_AUDIO_CHANNELS_MONO: u16 = 1;
pub const XSYNTH_AUDIO_CHANNELS_STEREO: u16 = 2;

pub const XSYNTH_INTERPOLATION_NEAREST: u16 = 0;
pub const XSYNTH_INTERPOLATION_LINEAR: u16 = 1;

pub const XSYNTH_ENVELOPE_CURVE_LINEAR: u8 = 0;
pub const XSYNTH_ENVELOPE_CURVE_EXPONENTIAL: u8 = 1;
