on:
  push:
    branches:
      - master

name: Publish

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Cargo
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Install ALSA
        run: sudo apt-get install -y libasound2-dev

      - name: Publish xsynth-soundfonts
        uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          args: -p xsynth-soundfonts
          ignore-unpublished-changes: true

      - name: Publish xsynth-core
        uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          args: -p xsynth-core
          ignore-unpublished-changes: true

      - name: Publish xsynth-realtime
        uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          args: -p xsynth-realtime
          ignore-unpublished-changes: true
